env:
  browser: true
  es6: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-eval:
    - error
  no-console:
    - off
